services:
  focalboard:
    image: nicoulaj/focalboard:latest
    container_name: focalboard
    ports:
      - 8080:8000
    restart: always
    volumes:
      - app_data:/opt/focalboard
    network_mode: bridge
volumes:
  app_data:
    driver: local
